Algoritmo "Medias"
// Disciplina   : [Lógica de programação e Algoritmos]
// Professora   : Sandra Maria Crippa 
// Descrição   : Calcular médias
// Autor(a)    : Josué Rios
// Data atual  : 13/08/2022
Var
// Seção de Declarações das variáveis
media, n1, n2 : real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Digite a nota 1")
Leia (n1)

Escreval ("Digite a nota 2")
Leia (n2)

media <- (n1 + n2)  / 2

Escreval ("Média:", media)


Fimalgoritmo