Algoritmo "p21 "
// Disciplina   : Lógica de Programação 
// Professora   : Sandra 

Var

   custo_espetaculo: real
   valor_convite: real
   quantidade_convite: real

Inicio

   escreva("Digite o custo do espetáculo R$:  ")
   leia(custo_espetaculo)

   escreva("Digite o valor do convite R$:  ")
   leia(valor_convite)

   quantidade_convite<-(custo_espetaculo/valor_convite)
   escreva("Quantidade de convites a ser vendido: ",quantidade_convite)
   leia(quantidade_convite)

Fimalgoritmo