Algoritmo "exercicio 8"
// Disciplina   : Lógica de Programação 
// Professora   : Sandra 
//
//
Var

   pes:inteiro
   polegada:real
   jarda:real
   milha:real

Inicio

   escreva("Digite a medida em Pés: ")
   leia(pes)

   polegada<-(pes*12)
   jarda<-(pes/3)
   milha<-((pes/3)/1760))
   escreva("Medida em Polegadas: ",polegada)
   escreva("Medida em Jardas: ",jarda)
   escreva("Medida em Mihas: ",milha)

Fimalgoritmo