Algoritmo "P12"
// Disciplina   : Lógica de Programação 
// Professora   : Sandra 



Var

   Numero: inteiro
   Numero_dois: inteiro
   numero_elevado: real

Inicio

   escreva ("Digite o primeiro numero: ")
   leia (Numero)

   escreva ("Digite o segundo numero: ")
   leia (Numero_dois)

   numero_elevado<-(Numero^Numero_dois)
   escreva("O valor do número é: ", numero_elevado)
   leia (numero_elevado)

Fimalgoritmo